
#pragma once

#ifndef __ENUMS_H_
#define __ENUMS_H_

#define Err_ErrorCreatingADOInstance "An error occured creating an instance of a Microsoft Data Object: "

#define CREATEADOINSTANCE(sp,riid,riidName)										\
{																				\
	HRESULT _hr = sp.CreateInstance( __uuidof( riid ) );						\
	if (FAILED(_hr)) {															\
		_bstr_t description = Err_ErrorCreatingADOInstance;						\
		description += riidName;												\
		description += ".\n";													\
		RAISE_ERROR_WITH_DESC(TSDBLogErr_ErrUnknown, _hr, description);	\
	}																			\
}

#define RsITEM(rs,n) rs->Fields->Item[n]->Value
#define CmdITEM(cmd,n) cmd->Parameters->Item[n]->Value

#define ksTypeName_Boolean		L"Boolean"
#define ksTypeName_String		L"String"
#define ksTypeName_Number		L"Number"
#define ksTypeName_Reference	L"Reference"
#define ksTypeName_Container	L"Container"

enum ETSDBLogErrors 
{
	TSDBLogErr_ErrUnknown					= -1,
	TSDBLogErr_FailureLoggingResults		= -2,
	TSDBLogErr_FailureToGetDataLink			= -3,
	TSDBLogErr_FailedInitConnection			= -4,
	TSDBLogErr_FailedToOpenStatement		= -5,
	TSDBLogErr_FailedToExecuteStatement		= -6,
	TSDBLogErr_FailedToInitStatement		= -7,
	TSDBLogErr_FailedToSetColumn			= -8,
	TSDBLogErr_FailedFilterExpression		= -9,
	TSDBLogErr_FailedPrecondition			= -10,
	TSDBLogErr_FailedNoStatementsDefined	= -11,
	TSDBLogErr_LoggingSequenceError			= -12,
	TSDBLogErr_SessionManagerError			= -13,
	TSDBLogErr_InvalidADOVersion			= -14,
	TSDBLogErr_ContainerTypeHeterogeneous	= -15,
	TSDBLogErr_ReferenceTypeNotSupported	= -16,
	TSDBLogErr_ContainerTypeNotSupported	= -17,
	TSDBLogErr_InvalidFormatValue			= -18,
	TSDBLogErr_InvalidColumnType			= -19,
	TSDBLogErr_FailedGetPrimaryKey			= -20,
	TSDBLogErr_InvalidTraversingOption		= -21,
	TSDBLogErr_InvalidResultType			= -22,
	TSDBLogErr_InvalidForeignKeyName		= -23 
};

enum ResultTypes {
    tsDBOptionsResultType_UUT = 0,
    tsDBOptionsResultType_Step = 1,
    tsDBOptionsResultType_Property = 2
};

enum StatementType {
    tsDBOptionsStatementType_RecordSet = 0,
    tsDBOptionsStatementType_Parameterized = 1,
    tsDBOptionsStatementType_Procedure = 2
};

enum CursorTypes {
    tsDBOptionsCursorType_Unspecified = -1,
    tsDBOptionsCursorType_ForwardOnly = 0,
    tsDBOptionsCursorType_Keyset = 1,
    tsDBOptionsCursorType_Dynamic = 2,
    tsDBOptionsCursorType_Static = 3
};

enum CursorLocations {
    tsDBOptionsCursorLocation_None = 0,
    tsDBOptionsCursorLocation_Server = 1,
    tsDBOptionsCursorLocation_Client = 2
};

enum LockTypes {
    tsDBOptionsLockType_Unspecified = -1,
    tsDBOptionsLockType_ReadOnly = 0,
    tsDBOptionsLockType_Pessimistic = 1,
    tsDBOptionsLockType_Optimistic = 2,
    tsDBOptionsLockType_BatchOptimistic = 3
};

enum ColDataType {
    tsDBOptionsColumnType_SmallInt = 0,
    tsDBOptionsColumnType_Integer = 1,
    tsDBOptionsColumnType_Float = 2,
    tsDBOptionsColumnType_DoublePrecision = 3,
    tsDBOptionsColumnType_Bstr = 4,
    tsDBOptionsColumnType_Boolean = 5,
    tsDBOptionsColumnType_Binary = 6,
    tsDBOptionsColumnType_DateTime = 7,
	tsDBOptionsColumnType_GUID = 8,
	tsDBOptionsColumnType_VarChar = 9
};

enum PrimaryKeyTypes {
    tsDBOptionsPrimaryKeyType_NotKey = -1,
    tsDBOptionsPrimaryKeyType_AutoGenerated = 0,
    tsDBOptionsPrimaryKeyType_StoreGuid = 1,
    tsDBOptionsPrimaryKeyType_GetValueFromStatement = 2,
    tsDBOptionsPrimaryKeyType_GetValueFromStoredProc = 3, //backward compatibility for 2.0
	tsDBOptionsPrimaryKeyType_GetValueFromStoredProcOutputValue = 3, //use this one for 3.0 and later
	tsDBOptionsPrimaryKeyType_GetValueFromStoredProcReturnValue = 4,
	tsDBOptionsPrimaryKeyType_UseExpression = 5
};

typedef long StatementTraverseOptions;

enum {
    tsDBOptionsTraverseOptions_Continue = 0,
    tsDBOptionsTraverseOptions_SkipResult = 1,
    tsDBOptionsTraverseOptions_SkipSubResult = 2,
    tsDBOptionsTraverseOptions_SkipBuiltinProperty = 4,
    tsDBOptionsTraverseOptions_SkipCustomProperty = 8,
    tsDBOptionsTraverseOptions_SkipAdditionalProperty = 16,
	/* tsDBOptionsTraverseOptions_SkipSubsequence = 32,*/
	tsDBOptionsTraverseOptions_UUTMask = tsDBOptionsTraverseOptions_SkipResult | tsDBOptionsTraverseOptions_SkipSubResult /* | tsDBOptionsTraverseOptions_SkipSubsequence */ ,
	tsDBOptionsTraverseOptions_StepMask = tsDBOptionsTraverseOptions_SkipResult | tsDBOptionsTraverseOptions_SkipSubResult /* | tsDBOptionsTraverseOptions_SkipSubsequence */ | tsDBOptionsTraverseOptions_SkipBuiltinProperty | tsDBOptionsTraverseOptions_SkipCustomProperty | tsDBOptionsTraverseOptions_SkipAdditionalProperty,
	tsDBOptionsTraverseOptions_PropertyMask = tsDBOptionsTraverseOptions_SkipResult | tsDBOptionsTraverseOptions_SkipSubResult
};

enum PropertyCategory {
    tsDBOptionsPropertyCategory_Unknown = 0,
    tsDBOptionsPropertyCategory_Builtin = 1,
    tsDBOptionsPropertyCategory_Custom = 2,
    tsDBOptionsPropertyCategory_Additional = 3,
    tsDBOptionsPropertyCategory_Parameter = 4,
};

#endif

